# Generated by Django 2.0.5 on 2019-01-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visibility', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('price_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=100)),
                ('offer_day_from', models.DateTimeField(blank=True)),
                ('offer_day_to', models.DateTimeField(blank=True)),
                ('quantity', models.IntegerField()),
                ('sku', models.IntegerField()),
                ('product_id', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
