# Generated by Django 2.0.5 on 2019-01-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
