# Generated by Django 2.0.5 on 2019-01-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190104_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_day_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_day_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
